server:
  port: 8083

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka

spring:
  application:
    name: producer
apollo:
  bootstrap:
    enabled: true
    namespaces: application
